apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: node-db-app
spec:
  # 3 Pods should exist at all times.
  replicas: 3
  selector:
    matchLabels:
      app: node-db-app
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: node-db-app
    spec:
      containers:
        - name: db-app
          image: shahbaazkyz/db-app:01
        - name: mongo
          image: mongo:latest
---
kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: node-db-app
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 3001
      targetPort: 3000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: node-db-app
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer
